version: 2

build:
  os: ubuntu-20.04

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, do not build your docs in additional formats
formats: []

# Optionally declare the Python requirements required to build your docs
python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
